---
sudo: false
language: cpp

os:
  - linux
# Do we actually need to run this on OSX?
# OSX is REALLY slow to test
#  - osx

matrix:
  fast_finish: true

env:
  matrix:
    # Latest 4.x Puppet (Covers LTS too)
    - PUPPET_GEM_VERSION="~> 4.0"
      RUBY_VER=2.1.9
      RAKE_TASK="test_languageserver test_languageserver_sidecar test_debugserver"
      BUNDLER_VERSION=1.17.3
    # Latest 5.x Puppet
    - PUPPET_GEM_VERSION="~> 5.0"
      RUBY_VER=2.4.1
      RAKE_TASK="test_languageserver test_languageserver_sidecar test_debugserver"
    # Latest 6.x Puppet
    - PUPPET_GEM_VERSION="~> 6.0"
      RUBY_VER=2.5.1
      RAKE_TASK="test_languageserver test_languageserver_sidecar test_debugserver"

    # Specific Puppet version testing
    - PUPPET_GEM_VERSION="5.1.0"
      RUBY_VER=2.4.1
      RAKE_TASK="test_languageserver"

    # Acceptance tests.
    - PUPPET_GEM_VERSION="~> 6.0"
      RUBY_VER=2.5.1
      RAKE_TASK="acceptance_languageserver"

    # Ruby tasks (style).  Puppet version is irrelevant
    - PUPPET_GEM_VERSION="> 0.0"
      RUBY_VER=2.5.1
      RAKE_TASK="rubocop"

before_install: true

install:
  - "export BUILD_VERSION=99.99.0-travis.$TRAVIS_BUILD_NUMBER"
  - if [ "$RUBY_VER" != "" ]; then
      rvm install $RUBY_VER;
      rvm use $RUBY_VER;
      ruby -v;
      gem -v;
      if [ "$BUNDLER_VERSION" != "" ]; then
        gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
      fi;
      bundle -v;
      bundle install;
      cat Gemfile.lock;
    fi

script:
  - if [ "$RAKE_TASK" != "" ]; then
      bundle exec rake $RAKE_TASK;
    fi
