version: 99.99.0-appv.{build}
clone_depth: 10
init:
- SET
image:
  - Visual Studio 2019

environment:
  matrix:
  # Latest 5.x Puppet
  - PUPPET_GEM_VERSION: "~> 5.0"
    RUBY_VER: 24-x64
    RAKE_TASK: "gem_revendor test_languageserver test_languageserver_sidecar test_debugserver"

  # Latest 6.x Puppet
  - PUPPET_GEM_VERSION: "~> 6.0"
    RUBY_VER: 25-x64
    RAKE_TASK: "gem_revendor test_languageserver test_languageserver_sidecar test_debugserver"

  # Latest 7.x Puppet
  - PUPPET_GEM_VERSION: "~> 7.0"
    RUBY_VER: 27-x64
    RAKE_TASK: "gem_revendor test_languageserver test_languageserver_sidecar test_debugserver"

  # Specific Puppet version testing
  - PUPPET_GEM_VERSION: "5.1.0"
    RUBY_VER: 24-x64
    RAKE_TASK: "gem_revendor test_languageserver"

  # Acceptance tests
  - PUPPET_GEM_VERSION: "~> 7.0"
    RUBY_VER: 27-x64
    RAKE_TASK: "gem_revendor acceptance_languageserver"

  # Ruby tasks (style, build release archives)
  - PUPPET_GEM_VERSION: "> 0.0" # Version is irrelevant
    RUBY_VER: 25-x64
    RAKE_TASK: rubocop build

matrix:
  fast_finish: true

install:
- ps: |
     if ($ENV:APPVEYOR_PULL_REQUEST_NUMBER -ne $null) {
       Write-Host "Setting build version..."
       $ENV:APPVEYOR_BUILD_VERSION | Out-File -FilePath 'lib\puppet_editor_services\VERSION' -Encoding ASCII -Confirm:$false -Force
     }

     if ($ENV:RUBY_VER -ne $null) {
       $ENV:Path = 'C:\Ruby' + $ENV:RUBY_VER + '\bin;' + $ENV:Path

       Write-Host "Ruby Version..."
       & ruby -v
       Write-Host "Gem Version..."
       & gem -v
       Write-Host "Bundle Version..."
       & bundle -v
       & bundle install

       type Gemfile.lock
     }

build: off

test_script:
- cmd: IF NOT "%RAKE_TASK%" == "" bundle exec rake %RAKE_TASK%

artifacts:
  - path: output/*.*
